apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: <cloud_registry>/<namespace>/backend-app:1.0
        securityContext:
          runAsNonRoot: true
        ports:
        - containerPort: 5000
