apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: <cloud_registry>/<namespace>/frontend-app:1.0
        securityContext:
          runAsNonRoot: true
        ports:
        - containerPort: 3000
